const CRYPTO_ISLAM_HALAL_SYMBOLS_RAW = `
0G 2Z 42 5IRE A2Z A8 AA AAX AB ABEL ABR ABT ACE ACE ACRIA ACU ADA ADI ADM ADS ADX AERGO AFT AGC AGENT AGENT AGI AGIX AGIXT AGLD AGON AGT AI16Z AI AI AI AIA AIA AIAI AIAV AICELL AIEPK AIFUN AIMX
AIN AIN AIO AION AIOT AIOZ AIST AITECH AIUS AIX AIXBT AKE AKI AKT ALCH ALEO ALEPH ALGO ALI ALL ALLIN ALPH ALPINE ALT ALU AMB AME AMO AMO AMP ANDR ANLOG ANS ANT ANYONE AO AOA AOP APE API3 APT APTM AQA AR
ARB ARC ARC ARCSOL ARDR AREA ARENA ARK ARKM ARPA ARRR ART ARTFI ARV ARVEX ARX ASCN ASI ASM ASP ASSIST ASTO ASTR ASTRA AT ATA ATH ATOM ATOMARC20 ATR ATS AU AUKI AURORA AUSD AUTOS AVA AVAAI AVAIL AVAX AVIVE AVN AVT AVTM
AWE AXIS AXL AZERO AZTEC B2 B3 B3TR BAD BAI BANANA BANANA BAND BASEDAI BAT BATCH BCH BCN BCUBE BCUT BDCA BDP BDX BDXN BEAMX BEE BEPRO BFC BGSC BICO BID BIDZ BIO BIOFI BITS BKN BLD BLESS BLOCX BLOK BLPT BLUAI BLUR BLY
BLZ BMT BOBA BOLTAI BOOM BOOST BORA BOS BOSON BOX BRCT BREV BRG BRIC BRISE BSAI BSV BTC BTCB BTF BTG BTM BTT BUILD BUSY BUY BVM BVT BYTE BZZ C4E CAI CAIR CAM CAMP CARR CARV CAU CBAI CBK CCD CDX CELDATA CELL
CELO CELR CENNZ CENS CERE CESS CFX CGC CGPT CHAPZ CHATAI CHEQ CHEX CHRP CHZ CIRUS CIRX CKB CLANKER CLBK CLEO CLORE CLS CLV CMD CND CNTM COA COAI COLLAT COLX COM3 COMAI COMBO COOKIE COOL CORAL CORE COREUM COS CQT CRAI CROS CROSS
CRP CRPT CRTAI CRTS CRU CSPR CTI CTK CTP CTRL CTSI CTXC CTY CUDIS CUDOS CVC CWEB CXT CYBER CYCON CYS DAG DAOX DAPP DARK DASH DATA DBC DC DCD DCK DCR DDMT DEAI DEGEN DENT DERO DESCI DEXE DGB DGC DGH DGRAM DHX
DIA DIAM DIMO DIN DIS DKA DL DLC DMAIL DMC DMCP DMD DMTR DN DNX DOAI DOGE DOMIN DOP2 DOP DORA DOT DPR DREP DREYAI DRGN DSYNC DTEC DTVC DUCK DUPE DUSK DVPN DX EAI EAT Eclipse ECOIN EDG EDGE EDGE EDGEN EDU EFX
EGLD EGO EIGEN EIN ELA ELAND ELF elizaOS ELSA EMC EMRLD EMT ENJ enqAI ENS ENSO ENX EPAY EPIC EPIC EPIK EPT EQTY ERA ES ESIM ESP ESPORTS ESX ETC ETH ETHO ETHW ETN EURC EURI EVDC EVER EVMOS EWT EYE F3 FCT FDUSD
FET FHE FIDA FIL FIO FIRO FITFI FLAI FLK FLOCK FLR FLT FLUX FLY FMC FOG FORT FRA FREE FRIC FROKAI FTN FTR FUEL FUND FX GAG GAIA GAIN GAIX GAL GALA GALAXIS GAME GAS GATA GB GEMAI GEOD GFAL GFT GHOST GHX GINOA
GLM GLMR GLQ GMM GMRX GMT GNY GO GOC GOMD GPS GPT GPUS GRASS GRIFFAIN GRIN GROW GRS GRT GTAI GTC GTH GURU GWEI HAHA HAI HASHAI HBAR HEART HEI HELIO HERO HEU HGPT HIDE HIENS3 HIGH HINT HIVE HLG HMND HMT HNS HNT
HOLO HONEY HOOK HOPR HOT HPB HPO HTR HYPER HYVE IAG IAI IAI ICE ICNT ICP ICX ID IDEA IDNA IDOS IFR IKA IMU IMX INF INI INIT INSP IO ION IOST IOT IOTA IOTX IP IPV IQ IRIS IRON IRYS ISME ISP ISSP
IVEX JASMY JCT JKC JKL JOBSEEK JOJO JU KAI KAIA KAITO KALIS KARCON KARRAT KAS KASTA KAT KCN KEEP KEY KGEN KGST KIN KIN KIP KITE KITEAI KLAY KLS KMA KMD KNET KOIN KOLZ KPN KRO KSM KTA KULA KYVE L3 LA LAI LAK3
LAMB LAT LAVA LAVITA LBC LENS LEOX LF LFT LGCT LIFE LIGHT LIME LINEA LINK LIORA LISA LITH LITKEY LIVE LKI LKY LL LMR LMT LOCK LOCUS LOOKS LOOM LOT LPT LRC LSK LSS LTC LUMIA LUNA LWP LYN LYX MAGIC MAIAR MAIGA MAN
MANA MAND MANTA MAPO MARSH MASA MASK MAT MATH MATIC MDS MDT SIX ME MEALY MERL METIS MFG MGO MICRO MINA MIND MINT MIRA MIX MLK MND MNSRY MNTC MOB MOBI MOBILE MOCA MON MORE MOVE MOVE MOVR MPC MPLX MSN MTL MTP MTV
MUA MVL MXC MYRIA MYST MYTH N3 NAI NAI NAM NAORIS NATIX NAVI NB NC NCDT NCT NEAR NEBL NEI NEON NERO NERTA NETVR NETX NetZ NEUR NEURON NEURONI NEUTON NEWT NEXA NEXUS NFC NFM NFP NFT NIBI NIGHT NIL NKN NLK NMT NND
NOCK NODE NODL NOS NRG NRK NRN NS NTMPI NTRN NTX NULS NUM NUMI NXN NXRA NXS NYM OAS OASC OBI OBOL OBORTECH OBOT OBT OBX OCEAN OCN OCTA OCTO OFN OJA OL OLAS OMG OMI OMN ON ONE ONG ONI OOOO OORT OP
OPEN OPEN OPEN OPENX OPG OPTI ORA ORAI ORB ORBR ORBS ORDI ORE ORT OVPP OVR OWL OXT OZO P2PS P3D PAAL PAL PALM PART PARTI PATEX PAYAI PDA PEAQ PEP PHA PHB PHI PHY PIB PIEVERSE PIGGY PIN PIP PIPE PIVX PLAY PLI
PLUME POKT POL POLYX POND POP PORT3 PORTAL POWER POWR PPC PRAI PRE PRGN PRIME PRL PRO PROM PROMPT PROPC PROPS PROPS PROVE PRQ PRX PUBLIC PUMLX PUNDIAI PUNDIX PUSH PVS PYI PYTH PYUSD QANX QBX QGOV QKC QNT QRL QTUM QUAI QUBIC QZN
RAD RADAR RAI RAIL RARE RARI RAVEN RAZE RCADE RCHV RDN RDO REAL REALIS REALKENDO REEF REI RENDER REQ RESCUE REV REX RIF RING RIO RIZ RIZE RLC RLUSD RNBW RNT ROAM RON ROOT ROSE ROUP ROY RSC RSR RSS3 RUNI RVN RWA RWAI
RWN RXD RYO RZR SABAI SAFE SAGA SAHARA SAITO SAND SAPIEN SAVM SC SC SCP SCR SCRT SDM SDN SDV SEI SEKOIA SENT SERO SERV SFP SHDW SHELL SHIDO SHM SHR SHX SIGN SIMAI SIMMI SINGULAR SKAI SKATE SKEY SKL SKR SKR SKYAI SLF
SLG SLN SMH SMRT SNAI SNIFT SNS SNS SNSY SNT SOGNI SOL SOLVE SOLVEX SOMI SOON SOPH SOSO SOUL SPACE SPEC SPORE SQD SQT SRC SRCH SRX SSS SSV ST STABLE STAMP STAR STAR STBU STEEM STFX STMX STOP STORAGENT STORE STORJ STOS STRAX
STREAM STX SUI SUKU SUP SUPRA SUT SVL SWARMS SWASH SWEAT SWFTC SWTCH SXP SXT SYL SYND SYNT SYS TA TAC TADA TAG TAI TAIKO TAKE TAKI TALE TALK TALK TANSSI TAO TARA TAT TEER TEL TET TFUEL THETA THREE THT TIA TIME TIMI
TLOS TMAI TNSR TOKAMAK TOKEN TON TORN TOWNS TRAC TRACE TRADE TRADE TRB TRIAS TRISIG TRL TRT TRUF TRUTH TRVL TRX TSLT TT TTD TTM TUSD TWT TX TXA U2U UB UBEX UBX UBXS UFI ULTIMA UMBRA UNQ UPC UPI UPP UQC US USAT
USDC USDG USDP USDT UTK UXLINK VAI VAIX VAL VANA VANA VANRY VARA VDA VDR VEE VELO VELVET VEMP VERTAI VET VEX VFY VIC VIDT VIRTUAL VIS VITA VITA VITE VR VRA VRSC VSYS VTC VTHO VV VVV VXV WAI WAL WAVES WAXP WBAI
WCT WEB3D WELL WEST WIFI WIN WIT WL WLD WMT WMTX WNK WOOP WORK WOW WRX WSDM WSI WSTOR WXT WYZ XAI XAN XAR XBG XCH XCN XCX XDAO XDB XDC XEC XEL XEM XEP XIDR XION XL1 XLM XMN XMR XNA XNO XNY
XPL XPR XR XRD XRPH XRT XSGD XSWAP XTAG XTER XTZ XU3O8 XUSD XVG XVM XYM XYO Y8U YNE YOM ZAMA ZANO ZAYA ZBCN ZBU ZEC ZELIX ZEN ZENQ ZENT ZERA ZETA ZIG ZIL ZIOX ZK ZK ZKC ZKJ ZKL ZKP ZKP ZKWASM ZNN
ZRC ZRO ZTC ZTX ZZZ
`;

const CRYPTO_ISLAM_HARAM_SYMBOLS_RAW = `
0x0 1000CHEMS 1000SATS 1CAT 1MBABYDOGE 2DAI 67 AAPLX ABOND ACS ACX AERO AEVO AFK AGX AI AI AI AIBB AIC AIDOGE AIKEK AIMBOT AIPAD AIRTOK AIS AIT AKRO ALCX ALLO ALPHA AMI AMPL AMU ANC ANI ANIME ANOME ANTS AOG AP APEX APR APU
APX AQT ARBS ARIAIP ARIX ARK ARKI ASC AST ASTER ASTEROID ASTRA ATOR AUDIO AVICI AVL AVNT AXS BABY BabyDoge BADGER BAKE BAL BAN BANANA BANANAS31 BANK BARD BAS BASED BASEX BB BCE BCP BDIN BEAT BEER2 BEER BEFI BERA BETA BETH BFUSD BGB
BGSOL BIFI BIRD BISO BIT BLENDR BLIND BLM BLOCK BLUE Blum BMX BNC BNSOL BNT BNX BOAM BOB BOB BOME BOND BONE BONK BOT BOT BR BRETT BROCCOLI714 Broccoli BROCK BSB BSW BSX BTR BTS BTW BTX BUBB BUILD BULLA BURGER C98 CAKE CANTO
CAS CAT CC CDL CDT CEL CET CETUS CFG CGV CGX CHAT CHECK CHESS CHILLGUY CHIP CKP CLFI CLH CLND CLO CLOUD CMC20 CO COCORO CODEX COMP CONV COPYCAT COQ CORL COW CPOOL CR7 CRCLon CREA CREAM CREDI CRP CRV CSIX CSKY CSTAR CSWAP
CTC CULT CULT CVP CVX CYBA CZ4 DADDY DAI DAM DAO DAPP DCI DCOIN DEEP DeepSeek DEFI DERI DF DFE DIONE DIVI DLC DNOW DODO DOGS DOLO DOP DORA DORKY DOWGE DOYR DRESS DRIFT DRV DSLA DSP DUEL DYDX EAVE ECHO EDEN EDGE EGP1
EGP ELON ELX EMPIRE EMR F5 ENA EPS ERG ETHFI ETS EUL EV EVAA EYWA FAKEAI FALCON FARM FARTCOIN FEG FF FHT FIGHT FINC FIRE FIS FLEX FLIP FLM FLOKI FLOW FLUID FLX FLZ FOGO FOLKS FOR FOREST FORTH Four FRAG FRBK FRONT FT
FTON FTT FUN FXF FXS GAME GARI GAU GEAR GEMS GEN GENIUS GF GFI Ghibli GIGA GIGGLE GIZA GIZA GMX GNS GOAT GOATED GODL GODS GORILLA GPT GPU GT GUA H1 HABIBI HAEDAL HANDY HARD HBD HDRO HEGIC HEMI HENAI HFT Hifi HIPPO HODL
HOME HOTKEY HTS HUMA HUSBY HYPE IDEX IDOL ILV IMGNAI IN INFOFI INFRA INJ INTR INV IR IXS IZZY JAGER JITOSOL JLP JOE JST JTO KARATE KAT KATA KAVA KEKE KEKIUS KERNEL KICKS KILO KING KINT KISHU KMNO KNC KOMA KP3R KTC KWAI LAB
LANLAN LAUNCHCOIN LAY3R LAYER LAYER LBP LBR LDO LEASH LEE LEO LEVER LIF3 LIGHT LIKE LINA LISTA LIT LITT LIZA LOGX LON LOUD LQTY LSD LSHARE LTD LUCE LUMA LUNC LUSH LYK LYNX M87 MAGA MAGMA MAHA MAMO MANYU MBD MBG MBL MBOX MCDULL
MDX MDX MEDXT MEFA MEFAI MELD MEME MEMEFI Memes MESH MET METFI METO MEW MEZO MFT MILK MINDFAK MIR MITO MKR MLN MM MMAI MMT MOCK MOG MONKY MOODENG MOOV MOROS MORPHO MOTHER MOVEZ MOZ MRLN MUBARAK MUBI MURATIAI MUSIC MX MY MYRO MYSTERY
MYX NAVX NAYM NEIRO NEO NEOS NEURA NEURAL NEXO NIZA NMR NODEX NOM NOON NORD NOT NOTAI NRWA NVDAX O4DX ODOS OGPU OKB ONDO ONT OOE OOKI OPM OPN OPUL ORACLE ORCA ORDER ORDS ORN ORNJ OSMO OVL PADD PAI PAI PAID PALAI
PALM PAW PAWS PAXE PBR PBUX PBX PELL PENDLE PENGUIN PEOPLE PEPE PEPEAI PERP PING PIPPIN PNDR PNG PNL PNUT POLK POLS POLX POLYDOGE PONKE Poof POPCAT POR PORTALS PRCL PROS PSTAKE PTB PUFFER PULSE PUMP PUMP PX PYTHIA QI QSHX QUICK QUQ R2
rats RAVE RAY RBN RDEX RDNT READY RECALL RED REN REP RESOLV RETARD REZ RFC RHEA RING RION RIVER ROLL RPL RTX RTX RUBYCOIN RUNE RVF RWA RWA SAKAI SALT SAMO SARA SAROS SBTC SCA SCALE SD SDAO SDEX SEN SEND SF SFUND SHADOW
SHIB SIGMA SIGMA SIS SKI SKY SLAY SLERF SLIM SMILE SNEK SNL SNS SNX SOLAMA SOLV SOLX SOS SPA SPECTRE SPELL SPK SPX SRM SSWP STABUL STARTUP STB STBL StETH STG STO STRD STRK STRUMP STUPID SUIA SUIP SUN SUNDOG SUP SUPER SUPR SURE
SUSHI SWAP SWCH SWELL SYN SYNTH SYRUP T1 TAB TAKER TAOBOT TBC TCOM TEA TENET TERMINUS THE THOR THQ TIDAL TKO TKT TMX TOR TOSHI TOWN TRADOOR TRAVA TREE TRIBE TRID TRN TROLL TROY TRU TRUST TRUU TRWA TST TST TUNA TURBO TURBOS TURTLE
TUT TYPE UAI UB UE UFT UGOR UMA UNFI UNI UNO UP UPTOP URO USD0 USD1 USDe USDS USDY USELESS USOR USTC USUAL VEGA VELA VELAR VELO VEREM VES VIB VINE VISTA VOLT VOOI VPAY VPS VRSW VRTX VUZZ VVS WAN WBETH WBTC WEBAI
WELL WET WHITE WHITEWHALE WIF WING WLAI WLFI WNXM WOJAK WOO WSM WWY XAG XALPHA XCHNG XLAB XMON XMW XNL XODEX XOXO XPIN XPRT XVS XYRO YAE YB YFI YND YU ZCX ZEAL ZEND ZENIQ ZEPH ZERC ZEREBRO ZERO ZEUS ZEUSETH ZEX ZKML ZKX
ZRO ZRX
`;

const CRYPTO_ISLAM_DOUBTFUL_SYMBOLS_RAW = `
AA ACE ACQ AGLA ALICE ANON ARTX ATN AUCTION AXM BERRY BIRB BLAST BORING BPX BTG CEEK CGN CHEEL CNV COLLECT CRO CYPR DAPPX DEGO DEVVE DFC DOSE DYM DYP ELECTRON ESE FEAR FOMO FOX FRAX FUSE GHST GNO GOLC GP GRIFT HANA HERA
HMSTR HUND HUSTLE INX JELLYJELLY JUP LILA LMWR LNQ LOOT LYM MANTRA MEV ML MNT MODE MOONED MOR MRX NABOX NGL NIGELLA NOM OAX PENGU PICA PINGPONG PLANCK PLANET PLS PRIMAL PYR QUILL RACA RDAC REAL RLS ROBO ROG ROOBEE SAI SAL SCLP SCPT
SENTIS SOCIAL SOLO SPHR TBK THR TITN TRC TRESTLE TRIA ULX UPO USBT VIA USDD VENOM VGX VLR VRX VSG WARD WEMIX WILD WLTH XCAD XGN XPX YBR ZAM ZBT ZCN ZORA
`;

const halalSymbols = toSymbolSet(CRYPTO_ISLAM_HALAL_SYMBOLS_RAW);
const haramSymbols = toSymbolSet(CRYPTO_ISLAM_HARAM_SYMBOLS_RAW);
const doubtfulSymbols = toSymbolSet(CRYPTO_ISLAM_DOUBTFUL_SYMBOLS_RAW);
const strictHalalSymbols = [...halalSymbols].filter((symbol) => !haramSymbols.has(symbol) && !doubtfulSymbols.has(symbol)).sort();

export function scoreHalalCoinSymbols(): string[] {
  return strictHalalSymbols;
}

export function matchesScoreHalalFilter(symbol: string, halal: boolean | undefined): boolean {
  if (halal === undefined) return true;
  const normalized = normalizeCoinSymbol(symbol);
  const isStrictHalal = normalized ? strictHalalSymbols.includes(normalized) : false;
  return halal ? isStrictHalal : !isStrictHalal;
}

function toSymbolSet(raw: string): Set<string> {
  return new Set(raw.split(/\s+/).map(normalizeCoinSymbol).filter(Boolean));
}

function normalizeCoinSymbol(symbol: string | null | undefined): string {
  return (symbol ?? '').trim().toUpperCase().replace(/^[#$]+/u, '').replace(/[^A-Z0-9]/gu, '');
}
