export const CRYPTO_ISLAM_HALAL_SYMBOLS_RAW = `
0G 2Z 42 5IRE A2Z A8 AA AAX AB ABEL ABR ABT ACE ACE ACRIA ACU ADA ADI ADM ADS ADX AERGO AFT AGC AGENT AGENT AGI AGIX AGIXT AGLD AGON AGT AI16Z AI AI AI AIA AIA AIAI AIAV AICELL AIEPK AIFUN AIMX
AIN AIN AIO AION AIOT AIOZ AIST AITECH AIUS AIX AIXBT AKE AKI AKT ALCH ALEO ALEPH ALGO ALI ALL ALLIN ALPH ALPINE ALT ALU AMB AME AMO AMO AMP ANDR ANLOG ANS ANT ANYONE AO AOA AOP APE API3 APT APTM AQA AR
ARB ARC ARC ARCSOL ARDR AREA ARENA ARK ARKM ARPA ARRR ART ARTFI ARV ARVEX ARX ASCN ASI ASM ASP ASSIST ASTO ASTR ASTRA AT ATA ATH ATOM ATOMARC20 ATR ATS AU AUKI AURORA AUSD AUTOS AVA AVAAI AVAIL AVAX AVIVE AVN AVT AVTM
AWE AXIS AXL AZERO AZTEC B2 B3 B3TR BAD BAI BANANA BANANA BAND BASEDAI BAT BATCH BCH BCN BCUBE BCUT BDCA BDP BDX BDXN BEAMX BEE BEPRO BFC BGSC BICO BID BIDZ BIO BIOFI BITS BKN BLD BLESS BLOCX BLOK BLPT BLUAI BLUR BLY
BLZ BMT BOBA BOLTAI BOOM BOOST BORA BOS BOSON BOX BRCT BREV BRG BRIC BRISE BSAI BSV BTC BTCB BTF BTG BTM BTT BUILD BUSY BUY BVM BVT BYTE BZZ C4E CAI CAIR CAM CAMP CARR CARV CAU CBAI CBK CCD CDX CELDATA CELL
CELO CELR CENNZ CENS CERE CESS CFX CGC CGPT CHAPZ CHATAI CHEQ CHEX CHRP CHZ CIRUS CIRX CKB CLANKER CLBK CLEO CLORE CLS CLV CMD CND CNTM COA COAI COLLAT COLX COM3 COMAI COMBO COOKIE COOL CORAL CORE COREUM COS CQT CRAI CROS CROSS
CRP CRPT CRTAI CRTS CRU CSPR CTI CTK CTP CTRL CTSI CTXC CTY CUDIS CUDOS CVC CWEB CXT CYBER CYCON CYS DAG DAOX DAPP DARK DASH DATA DBC DC DCD DCK DCR DDMT DEAI DEGEN DENT DERO DESCI DEXE DGB DGC DGH DGRAM DHX
DIA DIAM DIMO DIN DIS DKA DL DLC DMAIL DMC DMCP DMD DMTR DN DNX DOAI DOGE DOMIN DOP2 DOP DORA DOT DPR DREP DREYAI DRGN DSYNC DTEC DTVC DUCK DUPE DUSK DVPN DX EAI EAT Eclipse ECOIN EDG EDGE EDGE EDGEN EDU EFX
EGLD EGO EIGEN EIN ELA ELAND ELF elizaOS ELSA EMC EMRLD EMT ENJ enqAI ENS ENSO ENX EPAY EPIC EPIC EPIK EPT EQTY ERA ES ESIM ESP ESPORTS ESX ETC ETH ETHO ETHW ETN EURC EURI EVDC EVER EVMOS EWT EYE F3 FCT FDUSD
FET FHE FIDA FIL FIO FIRO FITFI FLAI FLK FLOCK FLR FLT FLUX FLY FMC FOG FORT FRA FREE FRIC FROKAI FTN FTR FUEL FUND FX GAG GAIA GAIN GAIX GAL GALA GALAXIS GAME GAS GATA GB GEMAI GEOD GFAL GFT GHOST GHX GINOA
GLM GLMR GLQ GMM GMRX GMT GNY GO GOC GOMD GPS GPT GPUS GRASS GRIFFAIN GRIN GROW GRS GRT GTAI GTC GTH GURU GWEI HAHA HAI HASHAI HBAR HEART HEI HELIO HERO HEU HGPT HIDE HIENS3 HIGH HINT HIVE HLG HMND HMT HNS HNT
HOLO HONEY HOOK HOPR HOT HPB HPO HTR HYPER HYVE IAG IAI IAI ICE ICNT ICP ICX ID IDEA IDNA IDOS IFR IKA IMU IMX INF INI INIT INSP IO ION IOST IOT IOTA IOTX IP IPV IQ IRIS IRON IRYS ISME ISP ISSP
IVEX JASMY JCT JKC JKL JOBSEEK JOJO JU KAI KAIA KAITO KALIS KARCON KARRAT KAS KASTA KAT KCN KEEP KEY KGEN KGST KIN KIN KIP KITE KITEAI KLAY KLS KMA KMD KNET KOIN KOLZ KPN KRO KSM KTA KULA KYVE L3 LA LAI LAK3
LAMB LAT LAVA LAVITA LBC LENS LEOX LF LFT LGCT LIFE LIGHT LIME LINEA LINK LIORA LISA LITH LITKEY LIVE LKI LKY LL LMR LMT LOCK LOCUS LOOKS LOOM LOT LPT LRC LSK LSS LTC LUMIA LUNA LWP LYN LYX MAGIC MAIAR MAIGA MAN
MANA MAND MANTA MAPO MARSH MASA MASK MAT MATH MATIC MDS MDT SIX ME MEALY MERL METIS MFG MGO MICRO MINA MIND MINT MIRA MIX MLK MND MNSRY MNTC MOB MOBI MOBILE MOCA MON MORE MOVE MOVE MOVR MPC MPLX MSN MTL MTP MTV
MUA MVL MXC MYRIA MYST MYTH N3 NAI NAI NAM NAORIS NATIX NAVI NB NC NCDT NCT NEAR NEBL NEI NEON NERO NERTA NETVR NETX NetZ NEUR NEURON NEURONI NEUTON NEWT NEXA NEXUS NFC NFM NFP NFT NIBI NIGHT NIL NKN NLK NMT NND
NOCK NODE NODL NOS NRG NRK NRN NS NTMPI NTRN NTX NULS NUM NUMI NXN NXRA NXS NYM OAS OASC OBI OBOL OBORTECH OBOT OBT OBX OCEAN OCN OCTA OCTO OFN OJA OL OLAS OMG OMI OMN ON ONE ONG ONI OOOO OORT OP
OPEN OPEN OPEN OPENX OPG OPTI ORA ORAI ORB ORBR ORBS ORDI ORE ORT OVPP OVR OWL OXT OZO P2PS P3D PAAL PAL PALM PART PARTI PATEX PAYAI PDA PEAQ PEP PHA PHB PHI PHY PIB PIEVERSE PIGGY PIN PIP PIPE PIVX PLAY PLI
PLUME POKT POL POLYX POND POP PORT3 PORTAL POWER POWR PPC PRAI PRE PRGN PRIME PRL PRO PROM PROMPT PROPC PROPS PROPS PROVE PRQ PRX PUBLIC PUMLX PUNDIAI PUNDIX PUSH PVS PYI PYTH PYUSD QANX QBX QGOV QKC QNT QRL QTUM QUAI QUBIC QZN
RAD RADAR RAI RAIL RARE RARI RAVEN RAZE RCADE RCHV RDN RDO REAL REALIS REALKENDO REEF REI RENDER REQ RESCUE REV REX RIF RING RIO RIZ RIZE RLC RLUSD RNBW RNT ROAM RON ROOT ROSE ROUP ROY RSC RSR RSS3 RUNI RVN RWA RWAI
RWN RXD RYO RZR SABAI SAFE SAGA SAHARA SAITO SAND SAPIEN SAVM SC SC SCP SCR SCRT SDM SDN SDV SEI SEKOIA SENT SERO SERV SFP SHDW SHELL SHIDO SHM SHR SHX SIGN SIMAI SIMMI SINGULAR SKAI SKATE SKEY SKL SKR SKR SKYAI SLF
SLG SLN SMH SMRT SNAI SNIFT SNS SNS SNSY SNT SOGNI SOL SOLVE SOLVEX SOMI SOON SOPH SOSO SOUL SPACE SPEC SPORE SQD SQT SRC SRCH SRX SSS SSV ST STABLE STAMP STAR STAR STBU STEEM STFX STMX STOP STORAGENT STORE STORJ STOS STRAX
STREAM STX SUI SUKU SUP SUPRA SUT SVL SWARMS SWASH SWEAT SWFTC SWTCH SXP SXT SYL SYND SYNT SYS TA TAC TADA TAG TAI TAIKO TAKE TAKI TALE TALK TALK TANSSI TAO TARA TAT TEER TEL TET TFUEL THETA THREE THT TIA TIME TIMI
TLOS TMAI TNSR TOKAMAK TOKEN TON TORN TOWNS TRAC TRACE TRADE TRADE TRB TRIAS TRISIG TRL TRT TRUF TRUTH TRVL TRX TSLT TT TTD TTM TUSD TWT TX TXA U2U UB UBEX UBX UBXS UFI ULTIMA UMBRA UNQ UPC UPI UPP UQC US USAT
USDC USDG USDP USDT UTK UXLINK VAI VAIX VAL VANA VANA VANRY VARA VDA VDR VEE VELO VELVET VEMP VERTAI VET VEX VFY VIC VIDT VIRTUAL VIS VITA VITA VITE VR VRA VRSC VSYS VTC VTHO VV VVV VXV WAI WAL WAVES WAXP WBAI
WCT WEB3D WELL WEST WIFI WIN WIT WL WLD WMT WMTX WNK WOOP WORK WOW WRX WSDM WSI WSTOR WXT WYZ XAI XAN XAR XBG XCH XCN XCX XDAO XDB XDC XEC XEL XEM XEP XIDR XION XL1 XLM XMN XMR XNA XNO XNY
XPL XPR XR XRD XRPH XRT XSGD XSWAP XTAG XTER XTZ XU3O8 XUSD XVG XVM XYM XYO Y8U YNE YOM ZAMA ZANO ZAYA ZBCN ZBU ZEC ZELIX ZEN ZENQ ZENT ZERA ZETA ZIG ZIL ZIOX ZK ZK ZKC ZKJ ZKL ZKP ZKP ZKWASM ZNN
ZRC ZRO ZTC ZTX ZZZ
`;
