export const CRYPTO_ISLAM_HARAM_SYMBOLS_RAW = `
0x0 1000CHEMS 1000SATS 1CAT 1MBABYDOGE 2DAI 67 AAPLX ABOND ACS ACX AERO AEVO AFK AGX AI AI AI AIBB AIC AIDOGE AIKEK AIMBOT AIPAD AIRTOK AIS AIT AKRO ALCX ALLO ALPHA AMI AMPL AMU ANC ANI ANIME ANOME ANTS AOG AP APEX APR APU
APX AQT ARBS ARIAIP ARIX ARK ARKI ASC AST ASTER ASTEROID ASTRA ATOR AUDIO AVICI AVL AVNT AXS BABY BabyDoge BADGER BAKE BAL BAN BANANA BANANAS31 BANK BARD BAS BASED BASEX BB BCE BCP BDIN BEAT BEER2 BEER BEFI BERA BETA BETH BFUSD BGB
BGSOL BIFI BIRD BISO BIT BLENDR BLIND BLM BLOCK BLUE Blum BMX BNC BNSOL BNT BNX BOAM BOB BOB BOME BOND BONE BONK BOT BOT BR BRETT BROCCOLI714 Broccoli BROCK BSB BSW BSX BTR BTS BTW BTX BUBB BUILD BULLA BURGER C98 CAKE CANTO
CAS CAT CC CDL CDT CEL CET CETUS CFG CGV CGX CHAT CHECK CHESS CHILLGUY CHIP CKP CLFI CLH CLND CLO CLOUD CMC20 CO COCORO CODEX COMP CONV COPYCAT COQ CORL COW CPOOL CR7 CRCLon CREA CREAM CREDI CRP CRV CSIX CSKY CSTAR CSWAP
CTC CULT CULT CVP CVX CYBA CZ4 DADDY DAI DAM DAO DAPP DCI DCOIN DEEP DeepSeek DEFI DERI DF DFE DIONE DIVI DLC DNOW DODO DOGS DOLO DOP DORA DORKY DOWGE DOYR DRESS DRIFT DRV DSLA DSP DUEL DYDX EAVE ECHO EDEN EDGE EGP1
EGP ELON ELX EMPIRE EMR F5 ENA EPS ERG ETHFI ETS EUL EV EVAA EYWA FAKEAI FALCON FARM FARTCOIN FEG FF FHT FIGHT FINC FIRE FIS FLEX FLIP FLM FLOKI FLOW FLUID FLX FLZ FOGO FOLKS FOR FOREST FORTH Four FRAG FRBK FRONT FT
FTON FTT FUN FXF FXS GAME GARI GAU GEAR GEMS GEN GENIUS GF GFI Ghibli GIGA GIGGLE GIZA GIZA GMX GNS GOAT GOATED GODL GODS GORILLA GPT GPU GT GUA H1 HABIBI HAEDAL HANDY HARD HBD HDRO HEGIC HEMI HENAI HFT Hifi HIPPO HODL
HOME HOTKEY HTS HUMA HUSBY HYPE IDEX IDOL ILV IMGNAI IN INFOFI INFRA INJ INTR INV IR IXS IZZY JAGER JITOSOL JLP JOE JST JTO KARATE KAT KATA KAVA KEKE KEKIUS KERNEL KICKS KILO KING KINT KISHU KMNO KNC KOMA KP3R KTC KWAI LAB
LANLAN LAUNCHCOIN LAY3R LAYER LAYER LBP LBR LDO LEASH LEE LEO LEVER LIF3 LIGHT LIKE LINA LISTA LIT LITT LIZA LOGX LON LOUD LQTY LSD LSHARE LTD LUCE LUMA LUNC LUSH LYK LYNX M87 MAGA MAGMA MAHA MAMO MANYU MBD MBG MBL MBOX MCDULL
MDX MDX MEDXT MEFA MEFAI MELD MEME MEMEFI Memes MESH MET METFI METO MEW MEZO MFT MILK MINDFAK MIR MITO MKR MLN MM MMAI MMT MOCK MOG MONKY MOODENG MOOV MOROS MORPHO MOTHER MOVEZ MOZ MRLN MUBARAK MUBI MURATIAI MUSIC MX MY MYRO MYSTERY
MYX NAVX NAYM NEIRO NEO NEOS NEURA NEURAL NEXO NIZA NMR NODEX NOM NOON NORD NOT NOTAI NRWA NVDAX O4DX ODOS OGPU OKB ONDO ONT OOE OOKI OPM OPN OPUL ORACLE ORCA ORDER ORDS ORN ORNJ OSMO OVL PADD PAI PAI PAID PALAI
PALM PAW PAWS PAXE PBR PBUX PBX PELL PENDLE PENGUIN PEOPLE PEPE PEPEAI PERP PING PIPPIN PNDR PNG PNL PNUT POLK POLS POLX POLYDOGE PONKE Poof POPCAT POR PORTALS PRCL PROS PSTAKE PTB PUFFER PULSE PUMP PUMP PX PYTHIA QI QSHX QUICK QUQ R2
rats RAVE RAY RBN RDEX RDNT READY RECALL RED REN REP RESOLV RETARD REZ RFC RHEA RING RION RIVER ROLL RPL RTX RTX RUBYCOIN RUNE RVF RWA RWA SAKAI SALT SAMO SARA SAROS SBTC SCA SCALE SD SDAO SDEX SEN SEND SF SFUND SHADOW
SHIB SIGMA SIGMA SIS SKI SKY SLAY SLERF SLIM SMILE SNEK SNL SNS SNX SOLAMA SOLV SOLX SOS SPA SPECTRE SPELL SPK SPX SRM SSWP STABUL STARTUP STB STBL StETH STG STO STRD STRK STRUMP STUPID SUIA SUIP SUN SUNDOG SUP SUPER SUPR SURE
SUSHI SWAP SWCH SWELL SYN SYNTH SYRUP T1 TAB TAKER TAOBOT TBC TCOM TEA TENET TERMINUS THE THOR THQ TIDAL TKO TKT TMX TOR TOSHI TOWN TRADOOR TRAVA TREE TRIBE TRID TRN TROLL TROY TRU TRUST TRUU TRWA TST TST TUNA TURBO TURBOS TURTLE
TUT TYPE UAI UB UE UFT UGOR UMA UNFI UNI UNO UP UPTOP URO USD0 USD1 USDe USDS USDY USELESS USOR USTC USUAL VEGA VELA VELAR VELO VEREM VES VIB VINE VISTA VOLT VOOI VPAY VPS VRSW VRTX VUZZ VVS WAN WBETH WBTC WEBAI
WELL WET WHITE WHITEWHALE WIF WING WLAI WLFI WNXM WOJAK WOO WSM WWY XAG XALPHA XCHNG XLAB XMON XMW XNL XODEX XOXO XPIN XPRT XVS XYRO YAE YB YFI YND YU ZCX ZEAL ZEND ZENIQ ZEPH ZERC ZEREBRO ZERO ZEUS ZEUSETH ZEX ZKML ZKX
ZRO ZRX
`;
