export const CRYPTO_ISLAM_DOUBTFUL_SYMBOLS_RAW = `
AA ACE ACQ AGLA ALICE ANON ARTX ATN AUCTION AXM BERRY BIRB BLAST BORING BPX BTG CEEK CGN CHEEL CNV COLLECT CRO CYPR DAPPX DEGO DEVVE DFC DOSE DYM DYP ELECTRON ESE FEAR FOMO FOX FRAX FUSE GHST GNO GOLC GP GRIFT HANA HERA
HMSTR HUND HUSTLE INX JELLYJELLY JUP LILA LMWR LNQ LOOT LYM MANTRA MEV ML MNT MODE MOONED MOR MRX NABOX NGL NIGELLA NOM OAX PENGU PICA PINGPONG PLANCK PLANET PLS PRIMAL PYR QUILL RACA RDAC REAL RLS ROBO ROG ROOBEE SAI SAL SCLP SCPT
SENTIS SOCIAL SOLO SPHR TBK THR TITN TRC TRESTLE TRIA ULX UPO USBT VIA USDD VENOM VGX VLR VRX VSG WARD WEMIX WILD WLTH XCAD XGN XPX YBR ZAM ZBT ZCN ZORA
`;
